apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ngx-oss-app1
spec:
  selector:
    matchLabels:
      app: ngx-oss-app1
  replicas: 4
  template:
    metadata:
      labels:
        app: ngx-oss-app1
    spec:
      containers:
      - name: ngx-oss-app1
        image: thedoberman/ngx-oss-app1:latest
        ports:
        - containerPort: 80
