kind: Service
apiVersion: v1
metadata:
  # Name of our service
  name: ngx-oss-app2-service
spec:
  type: NodePort
  externalIPs:
 #w1 nic ip
  - 10.1.1.7
  selector:
    # Will deliver external traffic to the pod holding each of our containers
    app: ngx-oss-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
